.code16
.global _start

_start:
	movb $0x0E, %ah
	movb $0x58, %al
	int $0x10
	xorw %ax, %ax
	movw %ax, %ds
	movw %ax, %es
	movw %ax, %ss
	movw $0x7C00, %sp
	movb %dl, (boot)
	movb $0x02, %ah
	movb $32, %al
	movw $0x0002, %cx
	movb $0x00, %dh
	movb (boot), %dl
	movw $0x8000, %bx
	int $0x13
	jc err
	movb $0x0E, %ah
	movb $0x58, %al
	int $0x10
	ljmp $0, $0x8000

err:
	movb $0x0E, %ah
	movb $'E', %al
	int $0x10
	hlt

boot: .byte 0

.org 510
.word 0xAA55
